services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - YANDEX_CLIENT_ID=your_yandex_client_id
      - YANDEX_CLIENT_SECRET=your_yandex_client_secret
      - SECRET_KEY=your_secret_key
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
